[versions]
accompanistPermissions = "0.36.0"
gson = "2.11.0"
coreSplashscreen = "1.0.1"
agp = "8.7.3"
kotlin = "2.0.0"
activityCompose = "1.10.0"
composeBom = "2025.01.00"
foundation = "1.7.6"
coroutines = "1.9.0"
lifecycle = "2.8.7"
okhttp = "4.12.0"
ossLicensesPlugin = "0.10.6"
playServicesOssLicenses = "17.1.0"
workRuntimeKtx = "2.10.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "foundation" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material3 = { module = "androidx.compose.material3:material3" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
